version: "3.1"
services:
  postgres:
    image: postgres
    container_name: "container_postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bd_root
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - proy_spring_network
  
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - proy_spring_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    networks:
      - proy_spring_network
    ports:
      - "5672:5672"
      - "15672:15672"
  

networks:
  proy_spring_network:
    driver: bridge

volumes:
  postgresql_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  vault_volume: